spring:
  application:
    name: video-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.168.200:3306/phone?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai&&allowMultiQueries=true
    username: root
    password: admin123456
server:
  port: 2003
mybatis:
  config-location: classpath:/db/mybatis-config.xml
#startup.cmd -m standalone